version: '3.9'

services:
  backend:
    build: ./backend
    container_name: progetto_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    container_name: progetto_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
