name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codice
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build container
      run: docker-compose -f docker-compose.yml build

    - name: Esegui test backend (facoltativo)
      run: |
        docker-compose -f docker-compose.yml up -d db
        docker-compose -f docker-compose.yml run backend npm test || echo "test falliti"
        docker-compose -f docker-compose.yml down

    - name: Deploy via SSH (solo su main)
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/project
          git pull origin main
          docker-compose down
          docker-compose up -d --build
