

services:
  frontend:
    build: ./frontend
    container_name: progetto_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    container_name: progetto_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env

  db:
    image: postgres:15
    container_name: progetto_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
       - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
