version: '3.9'

services:
  backend:
    build: ./backend
    container_name: progetto_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PG_USER: postgres
      PG_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: progetto_web

      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      STRIPE_SECRET_KEY:${{ secrets.STRIPE_SECRET_KEY }}

      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    container_name: progetto_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: progetto_web
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
